language: python

python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6
    - postgresql-client-9.6
    - postgis
    - postgresql-9.6-postgis-2.4-scripts

before_install:
  - /bin/bash -c "DEBIAN_FRONTEND=noninteractive sudo apt-get install -y tzdata"
  - sudo ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime
  - sudo dpkg-reconfigure --frontend noninteractive tzdata

env:
  global:
    # Flask env variables
    - TESTING=true
    - FLASK_APP="$TRAVIS_BUILD_DIR/manage"
    - OES_LOGLEVEL="DEBUG"
    - APP_SETTINGS="openelevationservice.server.config.TestingConfig"
    # PG env variables
#    - PGPORT=5433

# database creation
before_script:
  - sudo -u postgres psql -c "CREATE USER gis WITH PASSWORD 'gis';"
  - sudo -u postgres psql -c "ALTER USER gis WITH SUPERUSER;"
  - sudo -u postgres psql -c "CREATE DATABASE gis;"
  - sudo -u postgres psql -c "CREATE EXTENSION postgis;" -d gis
  - mv openelevationservice/server/ops_settings.sample.yml openelevationservice/server/ops_settings.yml

install: pip install -r requirements.txt

script: nosetests -v
