version: '2.2'
services:
  gunicorn_flask:
    #network_mode: "host"
    build: .
    volumes:
      - ./tiles/:/deploy/app/tiles
    ports:
      - "5020:5000"
    mem_limit: 6g
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - elevation-service-network

  elevation-postgis:
    image: postgis/postgis:17-3.5
    container_name: elevation-postgis
    volumes:
      - ./postgresql/:/var/lib/postgresql/data
      - ./postgis/20_create_extension_postgis_raster.sql:/docker-entrypoint-initdb.d/20_create_extension_postgis_raster.sql
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=gZwe5Nj
    ports:
      - 5432:5432
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - elevation-service-network
    
networks:
  elevation-service-network:
    driver: bridge
