---
attribution: "service by https://openrouteservice.org | data by http://srtm.csi.cgiar.org"
coord_precision: 1e-6
maximum_nodes: 2000
srtm_parameters:
  user: user
  password: pw
provider_parameters:
  table_name: "50_tiles"
  db_name: gis_test
  user_name: gis
  password: gis
  host: localhost
  port: 5432
