---
attribution: "service by https://openrouteservice.org | data by http://srtm.csi.cgiar.org or see https://github.com/tilezen/joerd_docker"
coord_precision: 1e-6
maximum_nodes: 2000
provider_parameters:
  table_name_srtm: srtm
  table_name_composite: composite
  db_name: oes_db
  user_name: gis
  password: gis
  host: localhost
  port: 5432
tables:
  - srtm:
      table_name: srtm
      sources:
        - srtm:
            url: http://data.cgiar-csi.org/srtm/tiles/GeoTIFF/
            srtm_parameters:
              user: user
              password: password
        - gmted:
            url: http://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/downloads/GMTED/Global_tiles_GMTED
            ys: [-90, -70, -50, -30, -10, 10, 30, 50, 70]
            xs: [-180, -150, -120, -90, -60, -30, 0, 30, 60, 90, 120, 150]
      extent:
        min_x: -1.406250
        min_y: 57.088515
        max_x: 15.820313
        max_y: 64.091408
  - composite:
      table_name: composite
      sources:
        - etopo1:
            url: https://www.ngdc.noaa.gov/mgg/global/relief/ETOPO1/data/bedrock/grid_registered/georeferenced_tiff/ETOPO1_Bed_g_geotiff.zip
      extent:
        min_x: 8.662891
        min_y: 49.395223
        max_x: 8.709412
        max_y: 49.423927
