---
attribution: "service by https://openrouteservice.org | data by http://srtm.csi.cgiar.org"
coord_precision: 1e-6
maximum_nodes: 2000
srtm_parameters:
  user: 
  password:
provider_parameters:
  table_name: oes_cgiar
  db_name: 
  user_name:
  password:
  host: localhost
  port: 5432
