---
attribution: "openrouteservice.org | NASA"
srtm_parameters:
  user: data_public
  password: GDdci
provider_parameters:
  table_name: oes_cgiar
  db_name: gis
  user_name: gis_admin
  password: admin
  host: localhost
  port: 5432
  port_tests: 5432
